file = {"LibInit/LibInit.lua","LibInit/factory.lua"}
format = "lunamark"
project = "LibInit"
dir = "docs"
title = "LibInit Documentation"
description = "LibInit should make using ACE3 even more simple and pleasant"
full_description = [[
LibInit offers clean methods to build a configuration table instead of directly fiddling with an Ace options table
Also adds quite a bunch of utilities for often needed tasks
]]
sort = true
not_luadoc=true
ignore = true
